title: Ryan Callaghan # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
<br>
Third Year Mechanical Engineering Student
<br>
"Contact me:"<br><br>
  <a href = "mailto: ryanmcallaghan3@gmail.com">ryanmcallaghan3@gmail.com</a> <br>
  <a href="tel:347-681-0910">347-681-0910</a> <br>
  <a href="https://www.linkedin.com/in/ryan-callaghan-396b27184/">LinkedIn</a> <br>
  <a href="https://www.facebook.com/ryan.callaghan.9406/">Facebook</a> <br>
  <a href=" https://www.instagram.com/ryancallaghan_/">Instagram</a> <br>
  <br><br>
  <a href="/pdf/Ryan Callaghan Resume.pdf">Resume</a> <br>
  
  
theme: jekyll-theme-minimal
google_analytics: G-1MESFSDNJ5 # your Google Analytics tracking ID here
