title: Ryan Callaghan # your name (or website title) here
logo: "/images/Headshotgithub.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Hi, I'm Ryan! <br><br>
 I am a junior studying Mechanical Engineering at Stevens Institute of Technology. I have experience with 3D design using SolidWorks, and AutoCAD. I have a passion for the medical device and technology industry and hope to pursue a career in this area.
 <br><br>
 Contact me:
  ryanmcallaghan3@gmail.com <br>
  347-681-0910
  
  <br><br>
  <a href="https://www.linkedin.com/in/ryan-callaghan-396b27184/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-1MESFSDNJ5 # your Google Analytics tracking ID here
