title: Ryan Callaghan # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

 Contact me:<br>
  ryanmcallaghan3@gmail.com <br>
  347-681-0910
  <br><br>
  <a href="/pdf/Ryan Callaghan Resume.pdf">Resume</a> <br>
  <a href="https://www.linkedin.com/in/ryan-callaghan-396b27184/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-1MESFSDNJ5 # your Google Analytics tracking ID here
